version: "3"

services:
  verana-front:
    image: veranalabs/verana-front:main
    ports:
      - 2904:3000
    build: 
      context: ../
      dockerfile: Dockerfile
    command: yarn start
    environment:
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:2904
      - NEXT_PUBLIC_VERANA_CHAIN_ID=vna-devnet-1
      - NEXT_PUBLIC_VERANA_CHAIN_NAME=VeranaDevnet1
      - NEXT_PUBLIC_VERANA_RPC_ENDPOINT=http://node1.devnet.verana.network:26657
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT=http://node1.devnet.verana.network:1317
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_GET_ACCOUNT=http://node1.devnet.verana.network:1317/verana/td/v1/get
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_LIST_DID=http://node1.devnet.verana.network:1317/verana/dd/v1/list
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_GET_DID=http://node1.devnet.verana.network:1317/verana/dd/v1/get
    networks:
      - verana

networks:
  verana:
    driver: bridge