version: "3"

services:
  verana-front:
    image: veranalabs/verana-front:main
    ports:
      - 2904:3000
    build: 
      context: ../
      dockerfile: Dockerfile
    command: yarn start
    environment:
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:2904
      - NEXT_PUBLIC_VERANA_CHAIN_ID=vna-testnet-1
      - NEXT_PUBLIC_VERANA_CHAIN_NAME=VeranaTestnet1
      - NEXT_PUBLIC_VERANA_RPC_ENDPOINT=https://rpc.testnet.verana.network
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT=https://api.testnet.verana.network
    networks:
      - verana

networks:
  verana:
    driver: bridge