import { env } from 'next-runtime-env'

export const readEnv = (key: string): string | undefined => env(key) || process.env[key]

const read = readEnv

export const VERANA_CHAIN_ID = read('NEXT_PUBLIC_VERANA_CHAIN_ID')
export const VERANA_CHAIN_NAME = read('NEXT_PUBLIC_VERANA_CHAIN_NAME')
export const VERANA_RPC_ENDPOINT = read('NEXT_PUBLIC_VERANA_RPC_ENDPOINT')
export const VERANA_REST_ENDPOINT = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT')
export const VERANA_EXPLORER_URL = read('NEXT_PUBLIC_VERANA_EXPLORER_URL')
export const VERANA_VISUALIZER_URL = read('NEXT_PUBLIC_VERANA_VISUALIZER_URL')
export const VERANA_TOPUP_VS = read('NEXT_PUBLIC_VERANA_TOPUP_VS')
export const VERANA_TOPUP_VS_HOST = VERANA_TOPUP_VS ? VERANA_TOPUP_VS.split(':')[2] : ''
export const VERANA_SIGN_DIRECT_MODE = read('NEXT_PUBLIC_VERANA_SIGN_DIRECT_MODE')

export const VERANA_INDEXER_BASE_URL = read('NEXT_PUBLIC_VERANA_INDEXER_BASE_URL')?.replace(/\/$/, '')

const indexerEndpoint = (key: string, path: string): string | undefined =>
  read(key) || (VERANA_INDEXER_BASE_URL ? `${VERANA_INDEXER_BASE_URL}/v4/${path}` : undefined)

export const VERANA_REST_ENDPOINT_ECOSYSTEM = indexerEndpoint('NEXT_PUBLIC_VERANA_REST_ENDPOINT_ECOSYSTEM', 'ecosystem')
export const VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA = indexerEndpoint(
  'NEXT_PUBLIC_VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA',
  'credential-schema'
)
export const VERANA_REST_ENDPOINT_PARTICIPANT = indexerEndpoint(
  'NEXT_PUBLIC_VERANA_REST_ENDPOINT_PARTICIPANT',
  'participant'
)
export const VERANA_REST_ENDPOINT_TRUST_DEPOSIT = indexerEndpoint(
  'NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_DEPOSIT',
  'trust-deposit'
)
export const VERANA_REST_ENDPOINT_CORPORATION = indexerEndpoint(
  'NEXT_PUBLIC_VERANA_REST_ENDPOINT_CORPORATION',
  'corporation'
)
export const VERANA_REST_ENDPOINT_DELEGATION = indexerEndpoint(
  'NEXT_PUBLIC_VERANA_REST_ENDPOINT_DELEGATION',
  'delegation'
)
export const VERANA_REST_ENDPOINT_GROUP = indexerEndpoint('NEXT_PUBLIC_VERANA_REST_ENDPOINT_GROUP', 'group')
export const VERANA_REST_ENDPOINT_INDEXER = indexerEndpoint('NEXT_PUBLIC_VERANA_REST_ENDPOINT_INDEXER', 'indexer')
export const VERANA_REST_ENDPOINT_METRICS = indexerEndpoint('NEXT_PUBLIC_VERANA_REST_ENDPOINT_METRICS', 'metrics')
export const VERANA_REST_ENDPOINT_VERIFIABLE_TRUST = indexerEndpoint(
  'NEXT_PUBLIC_VERANA_REST_ENDPOINT_VERIFIABLE_TRUST',
  'verifiable-trust'
)

export const VERANA_WEBSOCKET =
  read('NEXT_PUBLIC_VERANA_WEBSOCKET') ||
  (VERANA_INDEXER_BASE_URL ? `${VERANA_INDEXER_BASE_URL.replace(/^http/, 'ws')}/v4/indexer/subscribe` : undefined)

export const VERANA_CHAIN_PROVIDER_PROJECT_ID = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_PROJECT_ID')
export const VERANA_CHAIN_PROVIDER_RELAY_URL = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_RELAY_URL')
export const VERANA_CHAIN_PROVIDER_METADATA_NAME = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_NAME')
export const VERANA_CHAIN_PROVIDER_METADATA_DESCRIPTION = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_DESCRIPTION')
export const VERANA_CHAIN_PROVIDER_METADATA_URL = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_URL')
export const VERANA_CHAIN_PROVIDER_METADATA_ICONS = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_ICONS')

export const SESSION_LIFETIME_SECONDS = read('NEXT_PUBLIC_SESSION_LIFETIME_SECONDS')
export const LOW_BALANCE_WARN_UVNA = read('NEXT_PUBLIC_LOW_BALANCE_WARN_UVNA')
export const APP_VERSION = read('NEXT_PUBLIC_APP_VERSION')
