import { env } from 'next-runtime-env'

export const readEnv = (key: string): string | undefined => env(key) || process.env[key]

const read = readEnv

export const VERANA_CHAIN_ID = read('NEXT_PUBLIC_VERANA_CHAIN_ID')
export const VERANA_CHAIN_NAME = read('NEXT_PUBLIC_VERANA_CHAIN_NAME')
export const VERANA_RPC_ENDPOINT = read('NEXT_PUBLIC_VERANA_RPC_ENDPOINT')
export const VERANA_REST_ENDPOINT = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT')
export const VERANA_EXPLORER_URL = read('NEXT_PUBLIC_VERANA_EXPLORER_URL')
export const VERANA_VISUALIZER_URL = read('NEXT_PUBLIC_VERANA_VISUALIZER_URL')
export const VERANA_WEBSOCKET = read('NEXT_PUBLIC_VERANA_WEBSOCKET')
export const VERANA_TOPUP_VS = read('NEXT_PUBLIC_VERANA_TOPUP_VS')
export const VERANA_TOPUP_VS_HOST = VERANA_TOPUP_VS ? VERANA_TOPUP_VS.split(':')[2] : ''
export const VERANA_SIGN_DIRECT_MODE = read('NEXT_PUBLIC_VERANA_SIGN_DIRECT_MODE')

export const VERANA_REST_ENDPOINT_ECOSYSTEM = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_ECOSYSTEM')
export const VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA')
export const VERANA_REST_ENDPOINT_PARTICIPANT = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_PARTICIPANT')
export const VERANA_REST_ENDPOINT_DIGEST = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_DIGEST')
export const VERANA_REST_ENDPOINT_TRUST_DEPOSIT = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_DEPOSIT')
export const VERANA_REST_ENDPOINT_CORPORATION = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_CORPORATION')
export const VERANA_REST_ENDPOINT_DELEGATION = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_DELEGATION')
export const VERANA_REST_ENDPOINT_GOVERNANCE_FRAMEWORK = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_GOVERNANCE_FRAMEWORK')
export const VERANA_REST_ENDPOINT_INDEXER = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_INDEXER')
export const VERANA_REST_ENDPOINT_METRICS = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_METRICS')
export const VERANA_REST_ENDPOINT_RESOLVER = read('NEXT_PUBLIC_VERANA_REST_ENDPOINT_RESOLVER')

export const VERANA_CHAIN_PROVIDER_PROJECT_ID = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_PROJECT_ID')
export const VERANA_CHAIN_PROVIDER_RELAY_URL = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_RELAY_URL')
export const VERANA_CHAIN_PROVIDER_METADATA_NAME = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_NAME')
export const VERANA_CHAIN_PROVIDER_METADATA_DESCRIPTION = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_DESCRIPTION')
export const VERANA_CHAIN_PROVIDER_METADATA_URL = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_URL')
export const VERANA_CHAIN_PROVIDER_METADATA_ICONS = read('NEXT_PUBLIC_VERANA_CHAIN_PROVIDER_METADATA_ICONS')

export const SESSION_LIFETIME_SECONDS = read('NEXT_PUBLIC_SESSION_LIFETIME_SECONDS')
export const LOW_BALANCE_WARN_UVNA = read('NEXT_PUBLIC_LOW_BALANCE_WARN_UVNA')
export const APP_VERSION = read('NEXT_PUBLIC_APP_VERSION')
