version: "3"

services:
  verana-front:
    ports:
      - 2904:3000
    build: 
      context: ../
      dockerfile: Dockerfile
    command: yarn start
    environment:
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:2904
    networks:
      - verana

networks:
  verana:
    driver: bridge