'use client';

import PermissionTree, {TreeNode } from "@/ui/common/permission-tree";

const demoTree: TreeNode[] = [
  {
    id: "eco-1",
    role: "ECOSYSTEM",
    name: "Healthcare Ecosystem 2024",
    status: "active",
    icon: "crown",
    iconColorClass: "text-yellow-500",
    deposit: "234k VNA",
    fees: "issuance: 0.25 VNA verification: 0.25 VNA",
    stats: "issued: 1234 verified: 789",
    detail: {
      did: "did:verana:mainnet:z6Mk...A1B2",
      grantee: "verana1abc...xyz",
      permissionId: "12001",
      deposit: "45,000 VNA",
      effectiveFrom: "2024-01-15 14:30:00",
      effectiveUntil: "2024-12-15 14:30:00",
      country: "United States",
      issuedCredentials: "345",
      verifiedCredentials: "0",
      created: "2024-01-15 14:30:00",
      createdBy: "verana1def...uvw",
      modified: "2024-03-20 10:15:00",
      modifiedBy: "verana1ghi...rst",
      extended: "2024-06-10 16:45:00",
      extendedBy: "verana1jkl...opq",
      vpExpiration: "2025-01-15 14:30:00",
      vpLastStateChange: "2024-02-01 09:20:00",
      vpValidatorDeposit: "5,000 VNA",
      vpCurrentFees: "250 VNA",
      vpCurrentDeposit: "4,750 VNA",
      vpSummaryDigest: "sha256-abc123...",
      validationFees: "1.5 VNA",
      issuanceFees: "0.10 VNA",
      verificationFees: "0 VNA",
      slashedDeposit: "0 VNA",
      repaidDeposit: "0 VNA",
    },
    children: [
      {
        id: "eco-1-ig-dir",
        role: "GROUP",
        name: "Issuer Grantors (3)",
        icon: "folder",
        iconColorClass: "text-blue-500",
        joinLabel: "join",
        children: [
          {
            id: "eco-1-ig-1",
            role: "ISSUER_GRANTOR",
            name: "Primary Issuer Grantor",
            status: "active",
            icon: "crown",
            iconColorClass: "text-yellow-500",
            deposit: "125k VNA",
            fees: "issuance: 0.15 VNA verification: 0.15 VNA",
            stats: "issued: 567 verified: 234",
            children: [
              {
                id: "eco-1-ig-1-i-dir",
                role: "GROUP",
                name: "Issuers (2)",
                icon: "folder",
                iconColorClass: "text-green-500",
                joinLabel: "join",
                children: [
                  {
                    id: "eco-1-ig-1-i-1",
                    role: "ISSUER",
                    name: "Hospital Issuer A",
                    status: "expire soon",
                    icon: "eye",
                    iconColorClass: "text-gray-500",
                    deposit: "45k VNA",
                    fees: "issuance: 0.10 VNA",
                    stats: "issued: 345",
                    children: [
                      {
                        id: "eco-1-ig-1-i-1-h-dir",
                        role: "GROUP",
                        name: "Holders (2)",
                        icon: "folder",
                        iconColorClass: "text-pink-500",
                        joinLabel: "join",
                        children: [
                          {
                            id: "eco-1-ig-1-i-1-h-1",
                            role: "HOLDER",
                            name: "Patient Smith",
                            status: "active",
                            icon: "eye",
                            iconColorClass: "text-gray-500",
                            deposit: "5k VNA",
                          },
                          {
                            id: "eco-1-ig-1-i-1-h-2",
                            role: "HOLDER",
                            name: "Patient Johnson",
                            status: "active",
                            icon: "crown",
                            iconColorClass: "text-yellow-500",
                            deposit: "3k VNA",
                          },
                        ],
                      },
                    ],
                  },
                  {
                    id: "eco-1-ig-1-i-2",
                    role: "ISSUER",
                    name: "Clinic Issuer B",
                    status: "pending approbation",
                    icon: "crown",
                    iconColorClass: "text-yellow-500",
                    deposit: "30k VNA",
                    fees: "issuance: 0.12 VNA",
                    stats: "issued: 89",
                  },
                ],
              },
            ],
          },
          {
            id: "eco-1-ig-2",
            role: "ISSUER_GRANTOR",
            name: "Secondary Issuer Grantor",
            status: "expired",
            icon: "eye",
            iconColorClass: "text-gray-500",
            deposit: "75k VNA",
            fees: "issuance: 0.20 VNA verification: 0.18 VNA",
            stats: "issued: 123 verified: 67",
          },
        ],
      },
      {
        id: "eco-1-vg-dir",
        role: "GROUP",
        name: "Verifier Grantors (2)",
        icon: "folder",
        iconColorClass: "text-slate-500",
        joinLabel: "join",
        children: [
          {
            id: "eco-1-vg-1",
            role: "VERIFIER_GRANTOR",
            name: "Insurance Verifier Grantor",
            status: "active",
            icon: "crown",
            iconColorClass: "text-yellow-500",
            deposit: "90k VNA",
            fees: "verification: 0.22 VNA",
            stats: "verified: 456",
            children: [
              {
                id: "eco-1-vg-1-v-dir",
                role: "GROUP",
                name: "Verifiers (2)",
                icon: "folder",
                iconColorClass: "text-orange-500",
                joinLabel: "join",
                children: [
                  {
                    id: "eco-1-vg-1-v-1",
                    role: "VERIFIER",
                    name: "Insurance Company Alpha",
                    status: "active",
                    icon: "crown",
                    iconColorClass: "text-yellow-500",
                    deposit: "35k VNA",
                    fees: "verification: 0.18 VNA",
                    stats: "verified: 234",
                  },
                  {
                    id: "eco-1-vg-1-v-2",
                    role: "VERIFIER",
                    name: "Insurance Company Beta",
                    status: "slashed",
                    icon: "eye",
                    iconColorClass: "text-gray-500",
                    deposit: "20k VNA",
                    fees: "verification: 0.20 VNA",
                    stats: "verified: 89",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "eco-2",
    role: "ECOSYSTEM",
    name: "Finance Ecosystem 2024",
    status: "active",
    icon: "eye",
    iconColorClass: "text-gray-500",
    deposit: "189k VNA",
    fees: "issuance: 0.30 VNA verification: 0.28 VNA",
    stats: "issued: 890 verified: 567",
  },
];

export default function PermissionPage() {
  return (
      <PermissionTree demoTree={demoTree} />
  );
};