# Global configuration for the application
global:
  domain: devnet.verana.network

# General configuration
name: verana-frontend
host: app
replicas: 1

# Image configuration
image:
  pullPolicy: IfNotPresent
  repository: ""
  tag: ""

# Service configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# Node scheduling preferences
nodeSelector:
  kubernetes.io/hostname: cluster-utc-node-07efe5

# Environment variables consumed by the application 
env:
  NEXT_PUBLIC_PORT: "3000"
  NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
  NEXT_PUBLIC_VERANA_CHAIN_ID: "vna-devnet-1"
  NEXT_PUBLIC_VERANA_CHAIN_NAME: "VeranaDevnet1"
  NEXT_PUBLIC_VERANA_RPC_ENDPOINT: "https://rpc.devnet.verana.network"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT: "https://api.devnet.verana.network"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_ECOSYSTEM: "https://idx.devnet.verana.network/v4/ecosystem"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA: "https://idx.devnet.verana.network/v4/credential-schema"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_PARTICIPANT: "https://idx.devnet.verana.network/v4/participant"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_DIGEST: "https://idx.devnet.verana.network/v4/di"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_DEPOSIT: "https://idx.devnet.verana.network/v4/trust-deposit"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_CORPORATION: "https://idx.devnet.verana.network/v4/corporation"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_DELEGATION: "https://idx.devnet.verana.network/v4/delegation"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_GOVERNANCE_FRAMEWORK: "https://idx.devnet.verana.network/v4/governance-framework"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_INDEXER: "https://idx.devnet.verana.network/v4/indexer"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_METRICS: "https://idx.devnet.verana.network/v4/metrics"
  NEXT_PUBLIC_VERANA_REST_ENDPOINT_RESOLVER: "https://resolver.devnet.verana.network/v1"
  NEXT_PUBLIC_VERANA_EXPLORER_URL: "https://explorer.devnet.verana.network/Verana%20Devnet"
  NEXT_PUBLIC_VERANA_VISUALIZER_URL: "https://vis.devnet.verana.network"
  NEXT_PUBLIC_VERANA_TOPUP_VS: "did:web:faucet-vs.devnet.verana.network"
  NEXT_PUBLIC_VERANA_SIGN_DIRECT_MODE: "true"
  NEXT_PUBLIC_SESSION_LIFETIME_SECONDS: "86400"
  NEXT_PUBLIC_LOW_BALANCE_WARN_UVNA: "1000000"
  NEXT_PUBLIC_VERANA_WEBSOCKET: "wss://idx.devnet.verana.network/v4/indexer/subscribe"

# Additional env variables if needed (list of {name, value})
extraEnv: []

# Resource requests/limits for the frontend container
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Optional ingress configuration
ingress:
  enabled: true
  host: "{{ .Values.host }}.{{ .Values.global.domain }}"
  tlsSecret: public.{{ .Values.host }}.{{ .Values.global.domain }}-cert
  public:
    enableCors: true
  private:
    enableCors: true
    whitelistSourceRange: "" # e.g. "xxx.xx.xxx.xxx/32"
    tlsSecret: "private.{{ .Values.host }}.{{ .Values.global.domain }}-cert"
    host: ""
