version: "3"

services:
  verana-front:
    image: veranalabs/verana-front:main
    ports:
      - 2904:3000
    build: 
      context: ../
      dockerfile: Dockerfile
    command: yarn start
    environment:
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:2904
      - NEXT_PUBLIC_VERANA_CHAIN_ID=vna-devnet-1
      - NEXT_PUBLIC_VERANA_CHAIN_NAME=VeranaDevnet1
      - NEXT_PUBLIC_VERANA_RPC_ENDPOINT=https://rpc.devnet.verana.network
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT=https://api.devnet.verana.network
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_ECOSYSTEM=https://idx.devnet.verana.network/v4/ecosystem
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA=https://idx.devnet.verana.network/v4/credential-schema
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_PARTICIPANT=https://idx.devnet.verana.network/v4/participant
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_DIGEST=https://idx.devnet.verana.network/v4/di
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_DEPOSIT=https://idx.devnet.verana.network/v4/trust-deposit
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_CORPORATION=https://idx.devnet.verana.network/v4/corporation
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_DELEGATION=https://idx.devnet.verana.network/v4/delegation
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_GOVERNANCE_FRAMEWORK=https://idx.devnet.verana.network/v4/governance-framework
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_INDEXER=https://idx.devnet.verana.network/v4/indexer
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_METRICS=https://idx.devnet.verana.network/v4/metrics
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_RESOLVER=https://resolver.devnet.verana.network/v1
      - NEXT_PUBLIC_VERANA_EXPLORER_URL=https://explorer.devnet.verana.network/Verana%20Devnet
      - NEXT_PUBLIC_VERANA_SIGN_DIRECT_MODE=true
      - NEXT_PUBLIC_VERANA_WEBSOCKET=wss://idx.devnet.verana.network/v4/indexer/subscribe
    networks:
      - verana

networks:
  verana:
    driver: bridge
