// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: veranablockchain/trustdeposit/types.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "veranablockchain.trustdeposit";

/** TrustDeposit represents an account's trust deposit */
export interface TrustDeposit {
  account: string;
  share: Long;
  amount: Long;
  claimable: Long;
}

function createBaseTrustDeposit(): TrustDeposit {
  return { account: "", share: Long.UZERO, amount: Long.UZERO, claimable: Long.UZERO };
}

export const TrustDeposit = {
  encode(message: TrustDeposit, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.account !== "") {
      writer.uint32(10).string(message.account);
    }
    if (!message.share.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.share);
    }
    if (!message.amount.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.amount);
    }
    if (!message.claimable.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.claimable);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TrustDeposit {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrustDeposit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.account = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.share = reader.uint64() as Long;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.amount = reader.uint64() as Long;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.claimable = reader.uint64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrustDeposit {
    return {
      account: isSet(object.account) ? globalThis.String(object.account) : "",
      share: isSet(object.share) ? Long.fromValue(object.share) : Long.UZERO,
      amount: isSet(object.amount) ? Long.fromValue(object.amount) : Long.UZERO,
      claimable: isSet(object.claimable) ? Long.fromValue(object.claimable) : Long.UZERO,
    };
  },

  toJSON(message: TrustDeposit): unknown {
    const obj: any = {};
    if (message.account !== "") {
      obj.account = message.account;
    }
    if (!message.share.equals(Long.UZERO)) {
      obj.share = (message.share || Long.UZERO).toString();
    }
    if (!message.amount.equals(Long.UZERO)) {
      obj.amount = (message.amount || Long.UZERO).toString();
    }
    if (!message.claimable.equals(Long.UZERO)) {
      obj.claimable = (message.claimable || Long.UZERO).toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrustDeposit>, I>>(base?: I): TrustDeposit {
    return TrustDeposit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrustDeposit>, I>>(object: I): TrustDeposit {
    const message = createBaseTrustDeposit();
    message.account = object.account ?? "";
    message.share = (object.share !== undefined && object.share !== null) ? Long.fromValue(object.share) : Long.UZERO;
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? Long.fromValue(object.amount)
      : Long.UZERO;
    message.claimable = (object.claimable !== undefined && object.claimable !== null)
      ? Long.fromValue(object.claimable)
      : Long.UZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
