name: Continuous Deployment

env:
  IMAGE_NAME: verana-front
  DH_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  DH_TOKEN: ${{ secrets.DOCKER_HUB_PWD }}
  KUBECONFIG: ${{ secrets.OVH_KUBECONFIG }}
  VERANA_DEPLOY_PATH: verana-deploy
  CLUSTER_NODE: cluster-utc-node-07efe5

on:
  push:
    branches:
      - main    
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DH_USERNAME }}
          password: ${{ env.DH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker tag
        run: |
          SANITIZED_REF=${GITHUB_REF_NAME//\//-}
          echo "IMAGE_TAG=$SANITIZED_REF" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ github.ref_name == 'main' && format('{0}/{1}:latest', secrets.DOCKER_HUB_LOGIN, env.IMAGE_NAME) || '' }}


      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.9'

      - name: Deploy to OVH
        run: |
          set -euo pipefail
          echo "$KUBECONFIG" > k8s_config
          export KUBECONFIG=k8s_config

          declare -A CHAIN_IDS=( ["testnet"]="vna-testnet-1" ["devnet"]="vna-devnet-1" )
          declare -A CHAIN_NAMES=( ["testnet"]="VeranaTestnet1" ["devnet"]="VeranaDevnet1" )

          for ENV in testnet devnet; do
            VERANA_CHAIN_ID="${CHAIN_IDS[$ENV]}"
            VERANA_CHAIN_NAME="${CHAIN_NAMES[$ENV]}"

            export DEPLOYMENT_NAME="verana-${ENV}-frontend-app-deployment"
            export NEXT_PUBLIC_PORT=3000
            export NEXT_PUBLIC_BASE_URL=http://localhost:2904
            export NEXT_PUBLIC_VERANA_CHAIN_ID=$VERANA_CHAIN_ID
            export NEXT_PUBLIC_VERANA_CHAIN_NAME=$VERANA_CHAIN_NAME
            export NEXT_PUBLIC_VERANA_RPC_ENDPOINT="https://rpc.${ENV}.verana.network"
            export NEXT_PUBLIC_VERANA_REST_ENDPOINT="https://api.${ENV}.verana.network"
            export NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_DEPOSIT="https://api.${ENV}.verana.network/verana/td/v1"
            export NEXT_PUBLIC_VERANA_REST_ENDPOINT_DID="https://api.${ENV}.verana.network/verana/dd/v1"
            export NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_REGISTRY="https://api.${ENV}.verana.network/verana/tr/v1"
            export NEXT_PUBLIC_VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA="https://api.${ENV}.verana.network/verana/cs/v1"

            echo "Deploying to $ENV ($VERANA_CHAIN_ID)..."
            echo "Using image: veranalabs/$IMAGE_NAME:$IMAGE_TAG"
            kubectl create namespace $VERANA_CHAIN_ID --dry-run=client -o yaml | kubectl apply -f -
            kubectl delete -n $VERANA_CHAIN_ID deployment $DEPLOYMENT_NAME || true
            envsubst < kubernetes/verana-frontend-deployment.yaml | tee substituted-deployment.yaml | kubectl apply -f - --namespace=$VERANA_CHAIN_ID
          done
